### ISSUE TITLE
Documentation for date_happened is incorrect

### ISSUE THREAD

**Issue by adammw** [DataDog/dogstatsd-ruby#100]
The documentation for the `statsd.event()` method lists `:date_happened` as a possible option that can be passed in, as type Integer or nil, however passing in as an Integer results in a NoMethodError exception occurring:

```
"undefined method `delete' for 1535753113:Fixnum" location="/fluentd/vendor/bundle/ruby/2.3.0/gems/dogstatsd-ruby-3.3.0/lib/datadog/statsd.rb:399:in `remove_pipes'
```

Passing it in as a string posts the event successfully. Either the documentation needs to be updated, or the code calling `remove_pipes` should handle the case where an Integer is passed in.

**Comment by KSerrania** [comment]
#115 fixes this problem by correctly accepting `Integers` for `:date_happened`
