### ISSUE TITLE
Dogstatsd latest seems to be opening too many connections

### ISSUE THREAD

**Issue by rahul342** [DataDog/dogstatsd-ruby#141]
We were on `4.4.0` and upgraded to latest `4.7.0` and have been seeing issues where dogstatsd opens too many connections.

Here are some data from our application pod  -

```
# ss -s
Total: 92071
TCP:   331 (estab 9, closed 320, orphaned 0, timewait 25)
Transport Total     IP        IPv6
RAW	  0         0         0        
UDP	  28233     28232     1        
TCP	  11        10        1        
INET	  28244     28242     2        
FRAG	  0         0         0    
```
Most of the UDP ones are from dogstatsd

```
Recv-Q Send-Q       Local Address:Port      Peer Address:Port
0      0                127.0.0.1:32768        127.0.0.1:8125
0      0                127.0.0.1:32769        127.0.0.1:8125
0      0                127.0.0.1:32770        127.0.0.1:8125
0      0                127.0.0.1:32771        127.0.0.1:8125
0      0                127.0.0.1:32772        127.0.0.1:8125
0      0                127.0.0.1:32773        127.0.0.1:8125
0      0                127.0.0.1:32774        127.0.0.1:8125
0      0                127.0.0.1:32775        127.0.0.1:8125

```
...

```
Recv-Q Send-Q       Local Address:Port      Peer Address:Port
0  0   127.0.0.1:60988     127.0.0.1:8125
0  0   127.0.0.1:60989     127.0.0.1:8125
0  0   127.0.0.1:60990     127.0.0.1:8125
0  0   127.0.0.1:60991     127.0.0.1:8125
0  0   127.0.0.1:60992     127.0.0.1:8125
0  0   127.0.0.1:60993     127.0.0.1:8125
0  0   127.0.0.1:60994     127.0.0.1:8125
0  0   127.0.0.1:60995     127.0.0.1:8125
0  0   127.0.0.1:60996     127.0.0.1:8125
0  0   127.0.0.1:60997     127.0.0.1:8125
0  0   127.0.0.1:60998     127.0.0.1:8125
0  0   127.0.0.1:60999     127.0.0.1:8125


```

This then causes new connections to fails.

I believe there's probably something else in our infra that triggers this, but something with the current lib makes it worse and go into this loop of intiating connections.

On the same pod. I tried to write a message to the sock
```
Traceback (most recent call last):
        6: from /usr/local/bin/irb:23:in `<main>'
        5: from /usr/local/bin/irb:23:in `load'
        4: from /usr/local/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        3: from (irb):5
        2: from /usr/local/lib/ruby/2.6.0/socket.rb:321:in `sendmsg_nonblock'
        1: from /usr/local/lib/ruby/2.6.0/socket.rb:321:in `__sendmsg_nonblock'
IO::EAGAINWaitWritable (Resource temporarily unavailable - sendmsg(2) would block)
```

We downgraded back to 4.4.0 and haven't seen this happen again for the last 5 days.

Sorry I know this might not be enough to help you find the issue & cause, but just wanted to bring this to your notice. Feel free to close the issue if the info is not  enough.

**Comment by kbogtob** [comment]
Thanks for raising the issue!
It will be investigated and I will updated this issue.

**Comment by zachmccormick** [comment]
I submitted a support ticket, but we saw the same issue:

> If the datadog-agent restarts on a machine where we have a handful of unicorn (ruby) processes running and connected to DogStatsD running on port 8125, the new instance of datadog-agent is unable to claim port 8125 until the unicorn processes are stopped. We only saw this when upgrading dogstatsd-ruby from 4.0.0 to 4.7.0. Once we reverted, the problem went away.

**Comment by zachmccormick** [comment]
This causes some pretty nasty behaviors because it ends up using all of the UDP ports on the box, meaning DNS resolution will start to fail pretty often. We actually have to stop the unicorn processes, then restart datadog-agent, to get this to go away. Like I said - reverting seems to have fixed it.

**Comment by zachmccormick** [comment]
So I ran in a console with both 4.0.0 and 4.7.0 without anything listening on 8125:

```ruby
d = Datadog::Statsd.new('127.0.0.1', 8125)
while true do
  d.increment('foo')
end
```

then observed while it was running and not running the result of running a shell command:

```bash
lsof -n -i -s | grep UDP | grep ruby | wc -l
```

I get 0 ruby processes talking UDP when the loop isn't running, and maxed out (241 for me) when that is running (I have nothing listening on 8125). This is consistent no matter which version I'm using.

If I actually listen on that port via `nc -ulv 8125` (I'm on MacOS), then I don't get the explosion in UDP connections - the first one seems to establish just fine.

**Comment by zachmccormick** [comment]
I realized if I patch UDPConnection from:

```ruby
      def send_message(message)
        socket.send(message, 0)
      end
```

to

```ruby
      def send_message(message)
        socket.send(message, 0, host, port)
      end
```

then I think my usage of resolv-replace will cache the host -> addr lookup. I don't see an explosion of UDP socket usage when I do this replacement, even if I have nothing listening on that port.

**Comment by zachmccormick** [comment]
Ahh but then I don't see any data coming in when I use `nc -ulv 8125`, so that's obviously not the right solution either.

**Comment by zachmccormick** [comment]
This is my best guess fix. This change properly closes UDP sockets when the connection is bad: https://github.com/DataDog/dogstatsd-ruby/pull/142

**Comment by zachmccormick** [comment]
Ugh I was looking at 4.6 -> 4.7 this whole time and that wasn't where the bug was.

https://github.com/DataDog/dogstatsd-ruby/compare/v4.4.0...v4.5.0#diff-f7b44886d16ab8eb23deaed048ad0b10R49

When this started checking for ECONNREFUSED it introduced the behavior where it rapidly tries to re-establishing the socket connection without properly closing the socket it already had. The bug in socket handling was there before, but wasn't really going to be super evident since that retry code probably wasn't called super often. Now it gets called every other time you call `.send()` on a bad host (since the first time you send data to an invalid address via UDP it will return successful but the second time won't).

#142 fixes this if you want to still handle ECONNREFUSED

**Comment by kbogtob** [comment]
Closing as #143 was merged
