### ISSUE TITLE
Syntax Inquiry on Connection write method

### ISSUE THREAD

**Issue by Wmeng98** [DataDog/dogstatsd-ruby#150]
https://github.com/DataDog/dogstatsd-ruby/blob/0f1d768cc9fbac952c6b452297aaab7788a95d7e/lib/datadog/statsd/connection.rb#L28

Still new to ruby but why isn't this line written as `return true` to explicitly return the status on a "successful write"?

Thanks

**Comment by kbogtob** [comment]
The value of the last operation made in a block is the value returned by the block. Returns are optional in Ruby.

**Comment by Wmeng98** [comment]
> The value of the last operation made in a block is the value returned by the block. Returns are optional in Ruby.

Thanks, misread the indent inside the rescue statement.
