### ISSUE TITLE
batch in v4.9.0 was removed

### ISSUE THREAD

**Issue by matt-taylor** [DataDog/dogstatsd-ruby#168]
We recently upgraded to v4.9.0 from v4.8.3.

We heavily utilized the `batch` functionality in 4.8.3 https://github.com/DataDog/dogstatsd-ruby/blob/v4.8.3/lib/datadog/statsd.rb#L311-L315.

v4.9.0 does not have the batch method defined. We receive the following when trying to send a metric
```ruby
irb(main):018:0> statsd.batch { |b| b.increment('some_metric') } 
Traceback (most recent call last):
        1: from (irb):18
NoMethodError (undefined method `batch' for #<Datadog::Statsd:0x000055ab24412718>)
```
We have reverted back to using v4.8.3. 

Can the `batch` method be added back to the client?

edit:
Here is the diff `https://github.com/DataDog/dogstatsd-ruby/compare/v4.8.3...v4.9.0#diff-6ac7ed21ecf1fe04389730ce724b7502f0b1b17ccef2c1ccdd41bb8cd77ae6b1L311`

**Comment by dudo** [comment]
I'd like some reassurance that the DD team is committed to respecting SemVer going forward. This should have been a major version bump.

**Comment by rafthedeveloper** [comment]
+1, I tried to configure Sidekiq pro with Datadog as outlined here: https://docs.datadoghq.com/integrations/sidekiq/#overview and it no longer works due to the removal of this code. Will also revert back to v4.8.3 until this is resolved.

**Comment by remeh** [comment]
I'm very sorry for the issue.
This should indeed has been a version `5.0.0`. I'll remove the `4.9.0` gem, push a `4.9.1` reverting these changes to fix the version 4 and send changes in a major 5.0.0.

**Comment by matt-taylor** [comment]
Thank you handling this @remeh !

---

With regards to performance upgrades and the removal of batch in the new `v5.0.0`: What will be the preferred way to send multiple metrics at once? Or do the performance upgrades now allow us to send metrics individually without taking a hit on performance?

**Comment by remeh** [comment]
@matt-taylor an extract from the upcoming CHANGELOG/documentation changes:

What would have been written this way with the v4 API:

```ruby
require 'datadog/statsd' # with a v4.x version

statsd = Datadog::Statsd.new('127.0.0.1', 8125)

statsd.batch do |s|
  s.increment('example_metric.increment', tags: ['environment:dev'])
  s.gauge('example_metric.gauge', 123, tags: ['environment:dev'])
end
```

will have to be written this way with the v5 API:

```ruby
require 'datadog/statsd' # with a v5.x version

statsd = Datadog::Statsd.new('127.0.0.1', 8125)

statsd.increment('example_metric.increment', tags: ['environment:dev'])
statsd.gauge('example_metric.gauge', 123, tags: ['environment:dev'])

# synchronous flush
statsd.flush(sync: true)
```

The batching/buffering is done transparently by the client now. Also, if the buffer gets full, it will automatically flush when needed as well.

**Comment by matt-taylor** [comment]
Thank you for the confirmation on how to migrate to the new flow. We will start prepping for this change.

**Comment by hex337** [comment]
@remeh For the change to remove batches, in a threaded environment, are we guaranteed a flush when the thread dies, or do we have to ensure that on our end now?

**Comment by remeh** [comment]
@hex337 You will have to ensure it on your end before the thread is terminated.

**Comment by mperham** [comment]
A suggestion for the future: introduce the new API in 4.9 along with a deprecation notice for the old API then remove the old API in 5.0.
