### ISSUE TITLE
Options in initializer removed in 4.9.0

### ISSUE THREAD

**Issue by merrington** [DataDog/dogstatsd-ruby#169]
A handful of options were removed from `Statsd#initialize` in the 4.9.0 release, see the diff [here](https://github.com/DataDog/dogstatsd-ruby/compare/v4.8.3...v4.9.0#diff-6ac7ed21ecf1fe04389730ce724b7502f0b1b17ccef2c1ccdd41bb8cd77ae6b1L79-L83).
Initializing the statsd client with one of these options supplied results in an `ArgumentError`.
I don't see any mention of it in the Changelog and it feels like this could be considered a breaking change?

**Comment by remeh** [comment]
Hey @merrington, you are right this should have been considered a breaking change and should have been released as 5.0.0. Sorry for this issue, I've removed the 4.9.0 version for now, please pin version 4.8.3 for now and I'll release a major version 5.0.0 with these changes if you want to benefit of the performances improvements.

**Comment by merrington** [comment]
Thanks @remeh , we'll make sure to update our usage to take into account the changes for v5.0. In the meantime thanks for removing 4.9.0  👍
