### ISSUE TITLE
Restore `batch` method

### ISSUE THREAD

**Issue by mperham** [DataDog/dogstatsd-ruby#173]
This restores compatibility for downstream users. Why break apps when backwards compatibility is this easy?

```ruby
def batch
  yield self
  flush(sync: true)
end
```

Mark it as deprecated and remove it in v6.0 if you want.

**Comment by mperham** [comment]
This is also useful because statsd-ruby also has a `batch` method; this would keep the APIs closer in sync.

**Comment by kbogtob** [comment]
Hello @mperham ! This is clever and simple.
As the library doesn't work using the batches concept anymore, I simply removed the method and missed that we could write such a simple utility method. We'll add it in version 5.0.1, releasing soon. 
Thanks a lot!

**Comment by remeh** [comment]
Hey @mperham, thanks for this. A batch method has been reintroduced in 5.0.1. Please note that it doesn't behave exactly the same as in v4.x since a flush could be automatically triggered during the execution of the batch block.

**Comment by remeh** [comment]
Closing this since it has been reintroduced in 5.0.1 has a deprecated method.
