### ISSUE TITLE
Make this a source repo instead of a fork

### ISSUE THREAD

**Issue by davidcelis** [DataDog/dogstatsd-ruby#19]
GitHub isn't good about showing forks in search results, so when searching for the dogstatsd code, it never shows up. GitHub support would be able to remove the fork mode so that the typical flow involving deleting the repository wouldn't need to be followed

**Comment by miketheman** [comment]
I think one of our hopes and desires is that we fold dogstatsd-ruby and dogapi-rb into datadog.rb - so we won't have a disconnect between which lib to use and can start from a semi-clean slate with 0 changes to this repo.

**Comment by yannmh** [comment]
The impact is low. I am closing this issue in reflection of @miketheman's last comment.
