### ISSUE TITLE
Support for Rational?

### ISSUE THREAD

**Issue by tmorris-fiksu** [DataDog/dogstatsd-ruby#20]
When I pass a Rational () to `gauge`, it gets converted to something like:

```
[1] pry(main)> Rational(1,1).to_s
=> "1/1"
```

via the following line:

https://github.com/DataDog/dogstatsd-ruby/blob/v1.5.0/lib/statsd.rb#L356

```
send_stat "#{@prefix}#{stat}:#{delta}|#{type}#{rate}#{tags}"
```

Then, statsd understandably chokes on this.

Would you consider a PR that adds a line to this method:

```
  delta = delta.to_f if delta.class == "Rational"
```

?

Thx,
Trevor

**Comment by yannmh** [comment]
That's definitely a worthwhile change, thanks for bringing on the table @tmorris-fiksu. We'll certainly consider this for an upcoming release.

**Comment by djmitche** [comment]
This would still be accepted as a PR, but hasn't been added for 5 years, so seems unlikely to be critical to anyone's workflow.
