### ISSUE TITLE
Shutting down rails server is taking a long time since 5.1

### ISSUE THREAD

**Issue by Mathieuu** [DataDog/dogstatsd-ruby#201]
We have a pretty classic rails application (with sidekiq pro) and since we upgraded to 5.1, then 5.2 we have noticed that between sending CTRL-C to stop rails and the moment it actually stops, there is a 30 seconds delay.

```sh
[6544] - Worker 1 (PID: 6578) booted in 2.44s, phase: 0
^C
[6544] - Gracefully shutting down workers...
30 seconds later
[6544] === puma shutdown: 2021-07-20 10:26:50 -0700 ===
[6544] - Goodbye!
Exiting
```

Reverting to 5.0.1 fixes the problem and our server shuts down immediately. Let me know if I can provide any other useful information.

**Comment by remeh** [comment]
Hey @Mathieuu, thanks for having reported your issue.

I'll do a diff between `5.0.1` and recent versions and try to reproduce on my end to better understand what's happening. You confirm that's the only gem you're changing (i.e. downgrading dogstatsd-ruby) to fix the issue?

Can you maybe try using `5.2.0` but instantiating the client using `single_thread: true` and report if that is fixing your issue? That would give me some insights to understand what's happening. 🙇

**Comment by Mathieuu** [comment]
I tried with `5.2` with the following code:

```rb
# frozen_string_literal: true

module Statsd
  class Client
    delegate_missing_to :@client

    def initialize
      @client = Datadog::Statsd.new('localhost', 8125, single_thread: true)
    end
  end
end
```

Problem is still here. If you cannot pin point the exact commit, I can try to bisect between 5.0.1 and 5.1 if all commits in between are stable.

**Comment by Mathieuu** [comment]
It seems that upgrading ddtrace from 0.50.0 to 0.51.1 fixed the problem.
