### ISSUE TITLE
Documentation links under #metrics are broken

### ISSUE THREAD

**Issue by marcotc** [DataDog/dogstatsd-ruby#206]
Most of the links under the Metrics sections are pointing to pages that don't exist anymore: https://github.com/DataDog/dogstatsd-ruby#metrics

I wasn't able to find the new alternative locations, thus I'm opening an issue to capture this information.

**Comment by remeh** [comment]
Thanks for having reported this @marcotc, it seems to be broken on all our DogStatsD clients repositories, I'll look into this 👍

**Comment by remeh** [comment]
Fixed in #208
