### ISSUE TITLE
Ruby 3.0 support (#open method syntax)

### ISSUE THREAD

**Issue by clarkedb** [DataDog/dogstatsd-ruby#233]
Are there plans to support Ruby 3.0.x in a future release of `dogstatsd-ruby`? Or is there current support that just isn't documented?

**Comment by djmitche** [comment]
The README says:

> This gem supports and is tested on Ruby minor versions 2.1 through 3.0.

I'd be curious to know where you were looking for that documentation -- we can add it there, too :)

**Comment by ramfjord** [comment]
One issue with ruby 3 and this gem is with `Datadog::Statsd.open`, which relies on the old `*args` including `**kwargs` syntax.  Basically open no longer works with anything besides the positional `host`, `port` specified.  Might be a bit of a pain to get a version that's compatible with ruby both before and after 3.0 to fix this.

**Comment by ramfjord** [comment]
I don't think doc update is that great.  I'd honestly vote for remove the #open method which is broken and people can implement it themselves instead.  Alternatively, ruby 2.6 support is being EOL'd in a bit over one month.  Ruby 2.7 introduced a new argument forwarding `...` syntax` ([release notes](https://rubyreferences.github.io/rubychanges/2.7.html), [blog explanation](https://blog.saeloun.com/2019/12/04/ruby-2-7-adds-new-operator-for-arguments-forwarding) which could bridge the gap between 2.7 - 3+ versions and work on all of them, but it would mean dropping official support for ruby <= 2.6.

But I also don't know the original poster, and I'm not sure if there are any other incompatibilities with 3.0.

**Comment by djmitche** [comment]
We only just dropped 2.0 last week, so dropping 2.1 - 2.6 would be a big jump.
