### ISSUE TITLE
Make #239 ruby-2.2 compatible

### ISSUE THREAD

**Issue by djmitche** [DataDog/dogstatsd-ruby#243]
#239 fixed some poor error-handling, but did so in a way that's not ruby-2.2 compatible (see [pipeline](https://app.circleci.com/pipelines/github/DataDog/dogstatsd-ruby/109/workflows/7cf376f4-0e7c-452e-99bb-16153e023ad6/jobs/787)).  Let's expand that `.&` syntax to be compatible..

cc: @grosser

**Comment by grosser** [comment]
I think what we should do is:
- drop ruby <2.5 they are EOL and anyone using them most likely does not update their DD version anyway
- use GA for CI (see https://github.com/DataDog/dogstatsd-ruby/issues/241 for copy-paste example) or at least link circle-ci to the PRs

**Comment by djmitche** [comment]
We do still have folks using older Rubies, but we could plan that deprecation now ([the README](https://github.com/DataDog/dogstatsd-ruby#versioning) says we'll add a deprecation message in the previous minor)

I just changed CircleCI to build PRs - you're right on that count.

**Comment by grosser** [comment]
do folks using older rubies have to use the latest dd-client code though ?
(as in if they never bothered to update their rubies why would they update their dd-client 🤷 )

**Comment by grosser** [comment]
would still be nice to run this on GA since then the config is visible in the repo and can be changed as part of the PR
(or check in the circle-ci config if that's supported)

**Comment by djmitche** [comment]
https://github.com/DataDog/dogstatsd-ruby/pull/245 for the ruby versions, BTW.

**Comment by grosser** [comment]
somehow did not see the config, thx!
