### ISSUE TITLE
Potentially outdated guidance in public docs?

### ISSUE THREAD

**Issue by ivoanjo** [DataDog/dogstatsd-ruby#255]
Howdy! I was reviewing the Datadog public docs for all Ruby-related references (to see if anything related to dd-trace-rb was outdated and needed to be fixed) and noticed that in <https://docs.datadoghq.com/developers/dogstatsd/?code-lang=ruby#> in the Ruby section we state

> By default, Ruby DogStatsD client instances cannot be shared across processes but are thread-safe. Because of this, the parent process and each child process must create their own instances of the client or the buffering must be explicitly disabled by setting single_thread to true. See the [dogstatsd-ruby repo](https://github.com/DataDog/dogstatsd-ruby) on GitHub for more details.

This... seems like outdated guidance, right? I believe this no longer applies in recent releases?

**Comment by ivoanjo** [comment]
<https://docs.datadoghq.com/developers/dogstatsd/high_throughput/> also has a similar warning.

**Comment by djmitche** [comment]
https://github.com/DataDog/documentation/pull/13899
