### ISSUE TITLE
Re-using single thread client

### ISSUE THREAD

**Issue by j-manu** [DataDog/dogstatsd-ruby#264]
1. The README says

> When using the single_thread: true mode, instances of Datadog::Statsd are still thread-safe, but you may run into contention on heavily-threaded applications, so we don’t recommend (for performance reasons) reusing these instances.

What exactly is the contention mentioned here?

2. When re-using client with sender thread, it is recommended to flush. Why?
https://github.com/DataDog/dogstatsd-ruby/blob/5cb9a87154674f66ac740606d58315213ab7775b/examples/sidekiq_example.rb#L33  

What's the recommendation when re-using client with single thread?

**Comment by remeh** [comment]
Hey j-manu,

1. The contention is that everything runs sequentially with no threading whatsoever, you won't benefit from the multiple cores available on the host. Most scenarios are completely OK with the single thread use.

2. When it is possible, using an explicit manual flush is the best thing to do: you make sure that after the flush call, any metric buffered in the client is sent (or none if the buffer were already flushed). Even with the single thread mode which also uses a buffer.

HTH.
