### ISSUE TITLE
Should custom metrics use same client as ddtrace runtime_metrics?

### ISSUE THREAD

**Issue by ivanbrennan** [DataDog/dogstatsd-ruby#266]
In a Rails app that's using ddtrace and dogstatsd, the ddtrace configuration builds a dogstatsd client to collect runtime metrics,
```ruby
Datadog.configure do |c|
  # ...
  c.runtime_metrics.statsd = Datadog::Statsd.new(ENV.fetch("DD_AGENT_HOST", "localhost"), 8125)
  # ...
end
```

The dogstatsd readme [suggests](https://github.com/DataDog/dogstatsd-ruby#migrating-from-v4x-to-v5x),

> Using a singleton instance of the DogStatsD client instead of creating a new instance whenever you need one; this will let the buffering mechanism flush metrics regularly

Is it therefore recommended to use the same client for ddtrace runtime metrics and any custom metrics I want to collect? E.g.
```ruby
STATSD = Datadog::Statsd.new(ENV.fetch("DD_AGENT_HOST", "localhost"), 8125)

# ddtrace config
Datadog.configure do |c|
  # ...
  c.runtime_metrics.statsd = STATSD
  # ...
end

# my own domain logic, elsewhere in the app
STATSD.increment("example_metric_abc")
STATSD.increment("example_metric_xyz")
```

Or should I create two separate clients, one exclusively for ddtrace and another exclusively for my custom metrics?

**Comment by remeh** [comment]
Hi @ivanbrennan,

Not that it matters much, I would advise you to have a separated client for your custom metrics for different reasons:
  - you can use the options you want, different from the one used for the tracer (e.g. tags)
  - you can close it if not needed anymore (while the ddtrace one remains intact)
  - you can manage your flushes (even if that's doesn't matter much, especially if you're not sending a LOT of custom metrics)
  - ...

But once again, it doesn't matter much, both solution should work without troubles.
