### ISSUE TITLE
Calling increment throws exception

### ISSUE THREAD

**Issue by martyphee** [DataDog/dogstatsd-ruby#27]
Should increment function take a `by` parameter?  I'm using this with resque_metrics and it expects to call `statsd.increment` with `key` and `by`.

I've had to monkey patch their implementation.  Not a big deal, but I see other implementations out there which expect a number to increment by.

Esty daemon
https://github.com/etsy/statsd/blob/master/examples/StatsdClient.java

**Comment by yannmh** [comment]
That's definitely something we can add for the next release. 
Thanks for the suggestion @martyphee.

**Comment by martyphee** [comment]
Thanks.

**Comment by degemer** [comment]
Implemented in https://github.com/DataDog/dogstatsd-ruby/pull/33, will be part of 2.1.0.
