### ISSUE TITLE
Introduce a test mode

### ISSUE THREAD

**Issue by bobbytables** [DataDog/dogstatsd-ruby#28]
So when sending events, it would be nice to have a flag that we can enable a test mode of sorts. Where instead of sending events via UDP to datadog statsd server, they actually just go to an in-memory array. This allows us to test and make sure we're wired up to send data points correctly. Thoughts?

**Comment by yannmh** [comment]
Thanks for the further explanations @bobbytables.

I think that's already achievable. We do something similar in our tests plugging a "mocked" UDP socket to the Statsd instance: https://github.com/DataDog/dogstatsd-ruby/blob/master/spec/statsd_spec.rb#L12 and https://github.com/DataDog/dogstatsd-ruby/blob/master/spec/helper.rb#L15
