### ISSUE TITLE
Release new version with ipv6

### ISSUE THREAD

**Issue by gphat** [DataDog/dogstatsd-ruby#282]
Hey friends!

Could you release a new version that includes #280 so we don't have to run git ref versions to get it?

Thanks!!

**Comment by remeh** [comment]
Hey @gphat 
Sorry for the late reply. I'll create a release this week shipping your changes!

**Comment by remeh** [comment]
Hey @gphat, I forgot to update this thread but I released v5.6.1 last week! Closing your issue 👍

**Comment by gphat** [comment]
Np mate, I was watching and saw it went out. Tysm!
