### ISSUE TITLE
TCP support for non datadog usage

### ISSUE THREAD

**Issue by Koilanetroc** [DataDog/dogstatsd-ruby#285]
This statsd client is pretty good and I understand its supposed to be used with datadog as a part of its ecosystem. But this client is also can be used with other backends(like statsd or telegraf with statsd plugin). And sometimes its not possible to use udp because of some reasons. Are you interested in supporting tcp format for such cases?

I have a fork with tcp support, so if you are interested I can prepare a PR

**Comment by remeh** [comment]
Hey @Koilanetroc 

Thank you for reaching us about this! Supporting TCP is not part of `dogstatsd-ruby` roadmap for now. It does not mean you can't send a pull-request with your proposal, others people might see it and benefit from it. However, I don't plan on merging such a change as it implies future maintenance for something that's not planned for now. I hope you understand.
