### ISSUE TITLE
Allow a value to be specified for increment and decrement

### ISSUE THREAD

**Issue by devdazed** [DataDog/dogstatsd-ruby#29]
Currently increment and decrement assume that the only value one would want to increment by is 1.  It would be nice to add an optional value and default it to 1.

**Comment by yannmh** [comment]
Thanks for your suggestion @devdazed,

That's something we are working on for the upcoming release :ship:, c.f. #27.

**Comment by degemer** [comment]
Implemented in https://github.com/DataDog/dogstatsd-ruby/pull/33, will be part of 2.1.0.
