### ISSUE TITLE
NoMethodError in tag parsing if passed non-string

### ISSUE THREAD

**Issue by aselder** [DataDog/dogstatsd-ruby#41]
In a change of behavior from 1.6.0, Datadog::Statsd will blow up if an object that does not respond to `gsub` is passed in the tags array.

For instance:
Given `$statsd.timing("test", 0, tags: [MyClass])`

in 1.9.0, this works fine with MyClass coming through as "MyClass" in the tags

in 2.0.0 and greater, this gives the following error:
```
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/dogstatsd-ruby-2.1.0/lib/datadog/statsd.rb:349:in `remove_pipes'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/dogstatsd-ruby-2.1.0/lib/datadog/statsd.rb:345:in `escape_tag_content'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/dogstatsd-ruby-2.1.0/lib/datadog/statsd.rb:366:in `block in send_stats'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/dogstatsd-ruby-2.1.0/lib/datadog/statsd.rb:366:in `map'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/dogstatsd-ruby-2.1.0/lib/datadog/statsd.rb:366:in `send_stats'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/dogstatsd-ruby-2.1.0/lib/datadog/statsd.rb:188:in `timing'
	from (irb):13
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/deploy/.bundler/orders/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

I realize with the bump to 2.0.0, there are the possiblity of breaking changes, but if this is the new desired behavior, documentation in the change log warning of this would be appreciated.

**Comment by degemer** [comment]
Hello @aselder !
I'm sorry this happened to you, it was an unexpected feature of dogstatsd-ruby which was removed in `2.0.0` in order to validate the tags.
I think there is actually a warning in the changelog: https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#tags  - `Datadog::Statsd also validates that it receives an array of tags, and strips , and | from them.`.
It may not be visible enough though, do you think we should reformulate this part/insist on it ?
