### ISSUE TITLE
Error for Frozen Tag Array

### ISSUE THREAD

**Issue by IbottaBaier** [DataDog/dogstatsd-ruby#57]
When calling any `Datadog::Statsd` metric interface, if a frozen array is passed to the `tags:` parameter, an error is raised.

This is the code responsible in `Datadog::Statsd`:
```
def send_stats(stat, delta, type, opts={})
  ... 
  tag_arr = opts[:tags].to_a
  tag_arr.map! { |tag| t = tag.dup; escape_tag_content!(t); t }
  ...
end
```

If `opts[:tags]` is a frozen array, then `tag_arr` is also a frozen array, causing `map!` to error.

**Comment by KSerrania** [comment]
Fixed in #71
