### ISSUE TITLE
Patch v3.0.1 with the changes from 2 PRs that have been already merged

### ISSUE THREAD

**Issue by mikhailov** [DataDog/dogstatsd-ruby#64]
Hello!

We are looking to try latest changes from master, specifically: https://github.com/DataDog/dogstatsd-ruby/pull/51 and https://github.com/DataDog/dogstatsd-ruby/pull/53, both of them are part of next milestone: https://github.com/DataDog/dogstatsd-ruby/milestone/10?closed=1 

It would be awesome if you can release changes sooner, for instance, patch v3.0.1 with the changes from that PR #51 and #53!

Anatoly

**Comment by mikhailov** [comment]
cc @zippolyte as you merged them

**Comment by irabinovitch** [comment]
@mikhailov We have a few more PRs we need to merge before we release. We expect to have something out in December most likely.

**Comment by mikhailov** [comment]
v3.1.0 has been released https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#310--20171123
