### ISSUE TITLE
When batching metrics, possible to exhaust max UDP datagram size

### ISSUE THREAD

**Issue by jonmoter** [DataDog/dogstatsd-ruby#81]
I had an issue where I was sending metrics to dogstatsd from the ruby library. Each metric had 9 or 10 tags, and the tag values could be reasonably long. (Like a hostname in AWS.) I was batching the metrics, since I was using a lot of them.

I was noticing a lot of my tags were getting cut off at random places.  Like if I had a tag where I expected the value to be something like `db_type:read_replica`, I would see values like:

* `db_type:read_replica`
* `db_type:read_replic`
* `db_type:read_repli`
* `db_type:read_repl`
* etc.

After some digging and looking through the code, I looked up the [UDP packet structure](https://en.wikipedia.org/wiki/User_Datagram_Protocol#Packet_structure), and saw it had a max length of 65,527 bytes.

Here's the ruby logic for batching and flushing requests:

https://github.com/DataDog/dogstatsd-ruby/blob/3edece57c90dcfaf1c0f67b2493f0830c977adac/lib/datadog/statsd.rb#L439-L452

`@buffer` is an array, so it's just checking that the array the length of array is under a certain size. (By default, 50 elements.)  If each element in the array was, on average, more than 1,310 bytes, you'd wind up calling `send_to_socket` with a blob of data larger than the max size of a UDP packet.

I changed `@max_buffer_size` from 50 to 20 in my code, and my problems went away.

I recommend adding some logic so that either in `#send_stat` or `#flush_buffer`, it's smarter about chunking up the data.  If the size of `@buffer.join(NEW_LINE)` is larger than the packet limit, it can break it up into multiple sends.

**Comment by gmmeyer** [comment]
Hey @jonmoter! This is an important issue. @grosser's pull request (https://github.com/DataDog/dogstatsd-ruby/pull/86) should resolve this. We'll let you know when we put out a new version of the dsd gem!

**Comment by albertvaka** [comment]
Closing as this was fixed in https://github.com/DataDog/dogstatsd-ruby/pull/86
