### ISSUE TITLE
Next version date

### ISSUE THREAD

**Issue by TomMizrachi** [DataDog/dogstatsd-ruby#98]
Hey, 
Do you have a date for releasing a new version?
I saw you've added 'Batch' as a class, which will be very helpful to me.
Thanks for the great work! :)

**Comment by masci** [comment]
Hi @TomMizrachi , thanks for the heads-up!
I just released `4.0.0` on rubygems, let me know how it goes, the new version contains a lot of breaking changes.

**Comment by masci** [comment]
Hi @brettfishman the list is in the [changelog](https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md). Where are they missing?

**Comment by brettfishman** [comment]
Hi @masci - ah, yes - thanks. I was looking [here](https://github.com/DataDog/dogstatsd-ruby/releases).

**Comment by masci** [comment]
Ah my bad, completely forgot about that!
Thanks for letting me know!

**Comment by masci** [comment]
@brettfishman release page updated, thanks again!

**Comment by brettfishman** [comment]
@masci , no thank you!
